services:
  - type: web
    name: hbnb_v2_backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python3 -m app.scripts.fix_urls_prod
    startCommand: "gunicorn run:app"
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: "postgresql://myuser:mypassword@db:5432/hbnb_v2_db"
      - key: FLASK_SECRET_KEY
        value: "super-secret-flask"
      - key: JWT_SECRET_KEY
        value: "super-secret-jwt"
      - key: FLASK_ENV
        value: "production"
      - key: MAIL_SERVER
        value: "smtp.gmail.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USE_SSL
        value: "False"
      - key: MAIL_USERNAME
        value: "teckivoire@gmail.com"
      - key: MAIL_PASSWORD
        value: "ynsbluupsuxntxrr"
      - key: MAIL_DEFAULT_SENDER
        value: "teckivoire@gmail.com"
      - key: BREVO_API_KEY
        value: "PLACEHOLDER_FOR_BREVO_API_KEY"
      - key: BASE_URL
        value: "https://hbnb-v2-backend.onrender.com"
